name: click_functions_helper
description: Funções de apoio para manipular dados.
version: 1.0.0
repository: https://github.com/ferdead/click-functions-helper

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
